### PR TITLE
NOT done

### PR DESCRIPTION
**Pull request by jillianw**

### CODE REVIEW

**Comment by sumeetjain** [comment]
You're on the right track. This stuff is hard, so I'm glad you reached out.

First, take one problem at a time. Let's start exclusively with the with question about reversing the entire string.

It helps to have an example: `"Hello world."` is a good one for this.

So your algorithm (I'm copy/pasting from _your_ text):

| step | notes |
| --- | --- |
| a count of all of the characters in the string | 12 |
| one-at-a-time recall of each character backwards from the highest number | That's a very loaded step! :smile: I suggest breaking it down into smaller pieces. Imagine you were describing this process to a little nephew/niece who can do basic counting but not much else. They need help keeping track of which character they're on (for the "one-at-a-time recall" part), for example. See if you can get even more granular. |

So generally speaking, this is sounding good!

**Comment by jillianw** [comment]
Okay -- so I've broken it down a little further and I'm trying to come up with some code for it, but nothing even remotely successful yet. Here's my more detailed steps:

1) a = "Hello world."
2) .length to count all characters in "a"
3) create a loop to start at highest number and return each character, one at a time, in descending numerical order
4) loop stops after reaching 1
5) store results in new variable "b"  (???)
6) return "b"

If you could just tell me if I got off base, I'd appreciate that. Thank you so much.

**Comment by jillianw** [comment]
revised steps!!

1) a = "Hello world."
2) .length to count all characters in "a"
3) create new variable "b" to store results
4) create a loop to start at .length-1 and return each character, one at a time, in descending numerical order
5) loop continues while a (or b?) is >= 0
6) print "b"

**Comment by jillianw** [comment]
And here's what I've got for reversing the words in an array (let me know if you can't see the image). Similar to the reversal of characters but with the use of an array. I'm having a hell of a time figuring out (or understanding, rather) the code to use for this. I'm finding workable solutions but not comprehending some of the pieces of it. I'll keep trying. 

fullsizerender

**Comment by sumeetjain** [comment]
Your algorithms look good to me. Definitely on the right track, and I can certainly appreciate that the conversion to code can be difficult.

I suggest getting **any** code that you do feel comfortable with written down. That way you can submit it in small pieces, and I can give more specific guidance. For example, I imagine the first few steps of your algorithm (up to the `create new variable "b" to store results` step) are doable for you. Get that much coded at least, so I can see. Do what you can, and we'll take it from there :)

**Comment by jillianw** [comment]
Yes, you're right -- I understand some of the first chunk of it and think I've got it right (sorry, I'm still getting used to the idea of turning in an "incomplete assignment" :P ). This is for the reversal of all characters in a string:

a = "Hello world."
b = a.length - 1
 while b >= 0
 print.... ?

So, I've assigned the variable "a" with our "Hello world." string and also assigned a new variable "b" equalling the length of "a" minus one. I can't quite figure out if the -1 is significant because it's telling ruby to iterate backwards over the variable "a", or if it's necessary because if you're calling .length it's giving you the character count NOT starting at zero and that's what we need to get it to perform the loop properly, or <i>both</i>. I just know that it's what you have to do to make a loop. (Am I thinking too hard? I'm trying to look up the rationale but I'm not using the right search terms or something.) Lastly, I'm setting up the while loop so that while b >= 0, the loop is performed. I'd really like to know for sure how Ruby is going to know to start at the end and work backwards, though. And I get stuck at this point because I don't know what to tell Ruby to print while b >= 0.

**Comment by jillianw** [comment]
Deadline looming and trying to get on to the next exercise too (multiplying w/out *). Steps pictured below. As far as code goes, using the example numbers of 6 and 3, I've only gotten as far as a = 6 and b = 3. The third step of adding "a" "b" number of times is big -- I think there will be a lot of code going on there and I don't even know if it requires a loop. My feeling is that we're sticking with numbers here, but I don't know how to make something happen "b" number of times. 

img_0331

**Comment by jillianw** [comment]
Quick update on multiply w/out \* operator problem (I <b>did</b> figure out how to do something "b" number of times):

a = 6
b = 3
this_array = Array.new(b)  { a }
this_array.join(",")

I'm thinking I can get through some more of it but just wanted to share the progress so I don't waste your time!

Thanks!

**Comment by jillianw** [comment]
Ok... well I got this one to work now:

a = 6
b = 3
this_array = Array.new(b) {a}
sum = 0
this_array.each do |x|
  sum += x
end
puts sum 

I put the solution together piecemeal (by brushing up on blocks and searching for "how to add elements in an array"), so my understanding of how the sum part is working is alright but hazy. I couldn't have slapped that together off the top of my head is what I'm saying. Am I missing out on the value of these exercises if that is the case? I'm trying to get the concepts ingrained as I go along, but I'm finding that to be the hardest and most time-consuming part. Everything I'm seeing looks familiar to me, but the comprehension didn't stick in my head after the first exposure. 

Secondly, I don't know how to make it work with the "def" and "end" that are already present in Cloud 9. I removed them and raked it and got errors. Is there something I should be looking at to get a better grasp of how to put the code in these terms?

THANKS  :)

**Comment by jillianw** [comment]
...ok I'm looking back over the Anatomy of a Method section here. Whole nother layer of stuff I forgot about!  :0

http://ruby.bastardsbook.com/chapters/methods/

**Comment by sumeetjain** [comment]
First, don't sweat this particular assignment for the deadline. I can see you're working hard on it, and I don't want the anxiety to get in the way of your mental energy.

Second, if you have code to present, put it in the actual Ruby file, save it, and do the `git` steps. That way I can see it in the real file. It's okay that the tests don't pass–we both know the code is a work in progress.

Also, try to keep code/comments for each assignment separate. It'll make things confusing if we're talking about both the reverse-string and multiply-without-operator assignments here. :)

---

### For reverse-string assignment:

Let's dig into the algorithm you posted earlier:
1. `a = "Hello world."`
2. `.length` to count all characters in `a`
3. create new variable `b` to store results
4. create a loop to start at `.length-1` and return each character, one at a time, in descending numerical order
5. loop continues while a (or b?) is >= 0
6. `print "b"`

Elaborate on the "create a loop to start at `.length-1` and return each character, one at a time, in descending numerical order" step. That's a very meaty step–it'll almost certainly help to break it down into smaller pieces.

---

### For multiply-without-operator assignment:

Whatever code you have, get it submitted in the right assignment repository: https://github.com/jillianw/ruby-toy__multiply-without-operator I can reply there. Again, don't sweat the deadline too much–you're making good progress.

**Comment by sumeetjain** [comment]
First, a request from me: If you have **code**, then type it via Cloud9, save it, and do the `git` steps to sync with this Pull Request.

And if you have a **comment**, then just type it here as a comment in the conversation. It's hard for me to read long comments mixed in with code (The formatting is weird).

---

Second, don't change the name of the method. The tests that run automatically to check your work depend on the method names being the same as what we start you off with. So rename your method called `backwards` to what it was originally.

---

The algorithm you're working is below. I've turned it into a table and added a little bit of my own explanatory language to make it clearer, but it's still _your_ algorithm:

| Step | English | Code |
| --- | --- | --- |
| 1 | Start with a string that needs to be reversed. | `a = "Hello world."` |
| 2 | Count all characters in the string. | `a.length` |
| 3 | Create new variable to store results | `b = []` |
| 4 | Loop through characters one at a time, in descending numerical order. The loop should continue while `a >= 0` | ??? |
| 6 | The result we want is stored in the new variable from before. | `print "b"` |

Now Step 4 there definitely needs to be clarified. I'm going to ask some leading questions, and if you answer them I can use your own answers to guide you more effectively. So let's start with some basics:
- [x] What _number_ is used to denote the position of the _last_ item in an array?
- [x] How about the second-to-last? And third-to-last?

Post your answers below, and I'll reply quickly to help make this a conversation that ends with you getting a better translation of the algorithm into code.

**Comment by jillianw** [comment]
The last item in an array would be array[-1], so -1 I think is what you're asking for? The second to last and third to last would be array[-2] and array[-3].

**Comment by sumeetjain** [comment]
That's right.

Okay, I'm re-pasting your algorithm here for reference:

| Step | English | Code |
| --- | --- | --- |
| 1 | Start with a string that needs to be reversed. | `a = "Hello world."` |
| 2 | Count all characters in the string. | `a.length` |
| 3 | Create new variable to store results | `b = []` |
| 4 | Loop through characters one at a time, in descending numerical order. The loop should continue while `a >= 0` | ??? |
| 6 | The result we want is stored in the new variable from before. | `print "b"` |

And remember, we're digging into Step 4:

> Loop through characters one at a time, in descending numerical order. The loop should continue while `a >= 0`

The best way to think about loops is to think of them **not** as loops first. So if we wanted to go through the characters in `a = "Hello world"` one at a time in descending numerical order **without a loop**, we might do this:

``` ruby
a[-1].do_some_stuff
a[-2].do_some_stuff
a[-3].do_some_stuff
a[-4].do_some_stuff
a[-5].do_some_stuff
a[-6].do_some_stuff
a[-7].do_some_stuff
a[-8].do_some_stuff
a[-9].do_some_stuff
a[-10].do_some_stuff
a[-11].do_some_stuff
```

Of course, as programmers, we're hoping we can make that less redundant. Programmers are _pattern finders_–we love patterns! The pattern above is:

``` ruby
a[i].do_some_stuff
```

I just kept all the stuff that was the same and replaced the stuff that was different with a variable (which could have been `banana`, `x`, `num`, or whatever. I chose `i`.

So we have an _operation_ we want to do to each item in an array, and each time we do it, we want `i` to be something different. We know that the _first_ time we do it, we want `i` to be `-1`, and the second time for it to be `-2`, and the third time for it to be `-3`, and so on.

So let's re-write the algorithm:

| Step | English | Code |
| --- | --- | --- |
| 1 | Start with a string that needs to be reversed. | `a = "Hello world."` |
| 2 | Count all characters in the string. | `a.length` |
| 3 | Create new variable to store results | `b = []` |
| 4 | Create a counter variable for use in the loop that's coming up. | `i = -1` |
| 5 | Start a loop that runs one time per character. | ??? |
| 6 | Inside the loop, the operation to be run on each character is to put the character into `b` (the new variable we made above for storing our results) | ??? |
| 7 | Also inside the loop, change the value of `i` so that eventually the loop ends (and so that the next iteration of the loop deals with the _next_ character, and so on) | ??? |
| 8 | Eventually the loop ends | `end` :) |
| 9 | The result we want is stored in the new variable from before. | `print "b"` |

---

Consider this all and let me know what questions you have. Or take another stab at writing some code for it. I don't expect the above to be a "silver bullet" and clear everything up, so please don't hesitate to ask for clarifications or even to tell me that this isn't helpful at all. (I can take it!)

**Comment by jillianw** [comment]
I'll be honest -- I think I'm more confused than when I started. I'm just not getting it. I tried re-working the code according to your most recent advice but it's not working. I guess just let me know how far off I am at this point?

**Comment by sumeetjain** [comment]
No problem. There is a kind of upper-max on how useful instruction can be online :) I'm sorry for confusing things–and thank you for your patience! This stuff can be _very_ frustrating for new programmers, so know that you're not behind as far as I'm concerned.

Your code is not terribly far off from a solution, but it is missing some critical parts. Your code:

``` ruby
def reverse_characters
  a = "Hello world."
  a.length
  b = []
  a[i] = -1
    while a >= 0 do i 
  end
end
```

First, the method "signature" was `reverse_characters(str)` – and it should remain like that. So add back the `(str)` part.

The `str` code is a "parameter". It represents the text that's being reversed. So you don't need `a = "Hello world."` at all. Just assume/pretend some text is already stored in `str` for you to reverse.

Your updated code would look like this:

``` ruby
def reverse_characters(str)
  b = []
  a[i] = -1
    while a >= 0 do i 
  end
end
```

The goal now is to implement the algorithm.

Now, below I've written the answers you were missing–essentially spoilers. I don't want you to feel bad about this at all. Oftentimes the best way to make sense of something is to see it _done_ and then learn from the end-backwards. And you're not the only student for whom I've done this.

But review the algorithm and code below, see if coding it out in Cloud9 makes sense. And let me know if you have questions.

| Step | English | Code |
| --- | --- | --- |
| 1 | Start with a string that needs to be reversed. | `str` |
| 2 | Create new variable to store results | `b = []` |
| 3 | Create a counter variable for use in the loop that's coming up. | `i = -1` |
| 5 | Start a loop that runs one time per character. | `str.length.times do` |
| 6 | Inside the loop, the operation to be run on each character is to put the character into `b` (the new variable we made above for storing our results) | Given a string called `str` and a value of `-1` stored in `i`, you can call `str[i]` to get the last character. |
| 7 | Also inside the loop, change the value of `i` so that the next iteration of the loop deals with the _next_ character, and so on) | `i = i - 1` |
| 8 | Eventually the loop ends | `end` :) |
| 9 | The result we want is stored in the new variable from before. | `return b` |

**Comment by sumeetjain** [comment]
An example of that in practice: https://repl.it/Bem8

**Comment by jillianw** [comment]
Thanks for the encouragement. I'm glad to hear I'm not totally behind. I'm a <i>strongly</i> auditory learner (followed by tactile...) so I take an extra long time to process through things that are primarily visual. <i>And</i> I usually strongly prefer reverse-engineering things to figure out how they work, not work from scratch, so it's been a bit of a double whammy. As instructed, I'm not Googling exactly how to do each exercise, but only looking up individual parts of it isn't quite enough of a reverse-engineering process for it to all just click together for me quickly. And, of course, there are some concepts involved that I just plain don't get yet. But I'll keep trying. Some things are becoming clearer.

OK, this bit below -- this helps a LOT. I was not getting this:

<b>The str code is a "parameter". It represents the text that's being reversed. So you don't need a = "Hello world." at all. Just assume/pretend some text is already stored in str for you to reverse. <b/>

But I do have a few of questions still:

1) This line: <b>b << str[i]</b>. I feel like this is the first time I've seen << before. I looked it up and I'm seeing stuff about about binary shift and zeros and ones and it went WHOOSH right over my head. Does it mean "move left" essentially? Is that all I need to understand about it right now?

2) Arguments and parameters are the same thing, right? You said "str" is a parameter and I've seen it referred to elsewhere as an argument so I just want to be sure about the vocab. Further to that point, why is this page (http://ruby-doc.org/core-2.2.0/String.html) always referring to strings as str? Is there something about the significance of "str" that I'm missing? In the code you provided, it seems arbitrary -- is that correct?

3) The line that only has "b" on it -- can you explain that a bit? That works just the same as "return b"? Is return a necessary thing then? From what I've read it becomes necessary when the code is more... complicated. I guess that's the best I can describe it at the moment. 

I will see if I can quickly get these concepts applied to the word reversal part of the exercise.

Thanks again for your help, Sumeet.

**Comment by sumeetjain** [comment]
Solid questions. And thanks for the explanation about your learning preference. I would say that visual learners tend to have an advantage during Prep Work, and auditory learnings have a _significant_ advantage during class itself. Just saying–something to look forward to :)

Your questions:
1. `<<` is an "alias" for `push`. So with an array, doing `<<` is the same as doing `.push`.
2. Arguments and parameters are essentially synonymous. (They're not, actually. But they _are_ unless one's being pedantic.)
3. In Ruby, the last line of a method is assumed to be the return value. So `b` is the same as `return b` if it's the last line of the method. This is known as an "implicit return"–as opposed to "explicit return" which would include the `return` keyword.

**Comment by sumeetjain** [comment]
:+1: Nice!

**Pull request closed without merging**
