### PR TITLE
Done

### PR DESCRIPTION
**Pull request by mel-d**

### CODE REVIEW

**Comment by sumeetjain** [comment]
This works, but the methods are actually meant to be universal. That is, they should work for **any** string that's given. So what if `str` was actually `"Hello"` or the entire Gettysburg Address?

See if you can build an algorithm that accomplishes the code in your method using a counter or loop, so that it'll work for any string.

(And of course feel free to ask for more guidance.)

**Comment by mel-d** [comment]
I re-committed what I've been able to figure out as far as looping through both strings, but there's something wrong with the iteration line 'str2[0..-1] = str[-1..0]'. As far as I can tell from various Googlings, the '..' means it should iterate from the first index through the last one, so I'm not sure what I've done wrong. The program doesn't return any error messages, but I get 'nil' no matter the string that's entered.

**Comment by sumeetjain** [comment]
I can see how you would think that array ranges work like that. Unfortunately, that's not quite correct.

If you have an array `x = ["a", "b", "c", "d", "e", "f", "g"]`, here are some example usages of the `[]` method to get parts of it:

| Code | Result |
| --- | --- |
| `x[2]` | `"c"` - Simplest usage, right? |
| `x[-1]` | `"g"` - Same, pretty simple–starting from the end. |
| `x[2..4]` | `["c", "d", "e"]` - This is the **range** usage–indicated by the `..`. |
| `x[2,4]` | `["c", "d", "e", "f"]` - This is different from the range usage! With the `,` between the numbers, the first number is the index to start with and the second number is how many elements to return. That is, the first number is the index, and the second number is the maximum **length** of the new array to return. |

Now how about this:

``` ruby
`x[-6,4]`
```

It uses the comma, so the first number is the index–and the `-6` position is `"b"`. And the second number is how many elements to return. So:

```
["a", "b", "c", "d", "e", "f", "g"]
  -7   -6   -5   -4   -3   -2   -1
       ^ Start here.
       |----------------|
        1    2    3    4
                       ^ End here.
```

So that would return `["b", "c", "d", "e"]`.

What about `x[-6,-7]`? (Notice the `-7` value for the second parameter there.)

That would return `nil`, because it makes no sense! `-7` is not a valid maximum length–it makes no sense to say, "Start at element `-6` and give me the next `-7` elements."

How about a range though? What would `x[-6..-7]` return? (Notice the use of the `..` instead of a comma.)

You might think that it would work like this:

```
["a", "b", "c", "d", "e", "f", "g"]
  -7   -6   -5   -4   -3   -2   -1
       ^ Start here.
  |-----|
  ^ End here.          
```

But it doesn't :(

Ranges for an array go left-to-right... at least that's how they work in Ruby. So `x[-6..-7]` returns `nil`.

Think about this all and let me know if I can clarify anything. Ultimately, you'll need to find a different way to go element-by-element, starting from the end of course.

**Comment by mel-d** [comment]
Ok, I get what you said up there, and it makes sense. I feel like I'm
getting closer to the answer wanted. I just recommitted with this code:

def reverse_characters(str)
    str = str.split(//)
    x = str.length
    x.times {x = x - 1; print str[x]}
    return ?
end

def reverse_words(str)
    str = str.split(/ /)
    x = str.length
    x.times {x = x - 1; print str[x]}
    return ?
end

reverse_characters('Today is a good day')
puts
reverse_words('Today is a good day')

When I run the program on repl.it, it the x.times{} command is working, but
it's not actually returning what I want. 'return str[x]' returns only the
last loop of the {} command. What I'm looking for is a way to collect and
return the result of each loop of the {} command... I've been Googling
around for awhile and haven't found much that's very helpful. Puts and
print both have the same result, while putting return inside of the {}
makes the code stop after one loop. Do you have any input as to what I can
try?

Thank you for your ongoing help!
Melinda

**Comment by sumeetjain** [comment]
:+1: This is good to go.

Did you find your own answer to your question? Or were you still curious about that?

**Pull request closed without merging**
